ALTER TABLE `Permission` ADD `type` VARCHAR(100) DEFAULT NULL;
ALTER TABLE `Permission` ADD `description` VARCHAR(255) DEFAULT NULL;

UPDATE `Permission` SET `type` = 'CONCERN', `description` ='Can add or modify concerns' WHERE name = 'concerns:change:add:concern';
UPDATE `Permission` SET `type` = 'INTERNAL', `description` ='Merge concerns SQL data into ElasticSearch, used by the ETL' WHERE name = 'concerns:data:sync';
UPDATE `Permission` SET `type` = 'INTERNAL', `description` ='Register a new trainee with the concerns service, used by the ETL' WHERE name = 'concerns:register:trainee';
UPDATE `Permission` SET `type` = 'CONCERN', `description` ='Can view concerns' WHERE name = 'concerns:see:dbc:concerns';
UPDATE `Permission` SET `type` = 'INTERNAL', `description` ='Can view concerns for any trainee, used by the revalidation service' WHERE name = 'concerns:see:trainee:concerns';
UPDATE `Permission` SET `type` = 'CONNECTION', `description` ='Can action connection discrepancies, add or remove connection' WHERE name = 'connection:discrepancies:manage';
UPDATE `Permission` SET `type` = 'CONNECTION', `description` ='Can view connection discrepancies' WHERE name = 'connection:discrepancies:view';
UPDATE `Permission` SET `type` = 'NOTIFICATION', `description` ='Can create or change notifications' WHERE name = 'notification:change:add:notification';
UPDATE `Permission` SET `type` = 'PROFILE', `description` ='Can create and modify scaffolded profile entities' WHERE name = 'profile:add:modify:entities';
UPDATE `Permission` SET `type` = 'INTERNAL', `description` ='Can delete scaffolded profile entities' WHERE name = 'profile:delete:entities';
UPDATE `Permission` SET `type` = 'INTERNAL', `description` ='Used by the revalidation service to get RO information when submitting to GMC' WHERE name = 'profile:get:ro:user';
UPDATE `Permission` SET `type` = 'INTERNAL', `description` ='Used by the revalidation service to get the admins list for given DBCs' WHERE name = 'profile:get:users';
UPDATE `Permission` SET `type` = 'PROFILE', `description` ='Can view scaffolded profile entities' WHERE name = 'profile:view:entities';
UPDATE `Permission` SET `type` = 'PCS', `description` ='Can create and modify programmes' WHERE name = 'programme:add:modify';
UPDATE `Permission` SET `type` = 'INTERNAL', `description` ='Used by the ETL to upsert intrepid data in bulk' WHERE name = 'programme:bulk:add:modify';
UPDATE `Permission` SET `type` = 'PCS', `description` ='Can view programmes' WHERE name = 'programme:view';
UPDATE `Permission` SET `type` = 'PCS', `description` ='Can create and modify curricula' WHERE name = 'curriculum:add:modify';
UPDATE `Permission` SET `type` = 'INTERNAL', `description` ='Used by the ETL to upsert intrepid data in bulk' WHERE name = 'curriculum:bulk:add:modify';
UPDATE `Permission` SET `type` = 'PCS', `description` ='Can view curricula' WHERE name = 'curriculum:view';
UPDATE `Permission` SET `type` = 'REFERENCE', `description` ='Can create and modify reference entities' WHERE name = 'reference:add:modify:entities';
UPDATE `Permission` SET `type` = 'INTERNAL', `description` ='Can delete reference entities' WHERE name = 'reference:delete:entities';
UPDATE `Permission` SET `type` = 'REVALIDATION', `description` ='Can assign an admin to a revalidation episode' WHERE name = 'revalidation:assign:admin';
UPDATE `Permission` SET `type` = 'REVALIDATION', `description` ='Can create and modify revalidation trainee notes' WHERE name = 'revalidation:change:add:note';
UPDATE `Permission` SET `type` = 'INTERNAL', `description` ='Used by the ETL to sync revalidation SQL data with ElasticSearch indexes' WHERE name = 'revalidation:data:sync';
UPDATE `Permission` SET `type` = 'INTERNAL', `description` ='Used manually if the snapshot archive should fail when submitting a recommendation' WHERE name = 'revalidation:manual:archive';
UPDATE `Permission` SET `type` = 'REVALIDATION', `description` ='Can fill in and submit the provide recommendation form' WHERE name = 'revalidation:provide:recommendation';
UPDATE `Permission` SET `type` = 'INTERNAL', `description` ='Used by the ETL to register new trainees with the revalidation service' WHERE name = 'revalidation:register:trainee';
UPDATE `Permission` SET `type` = 'REVALIDATION', `description` ='Can view revalidation episodes and trainees' WHERE name = 'revalidation:see:dbc:trainees';
UPDATE `Permission` SET `type` = 'REVALIDATION', `description` ='Can submit a recomemndation to GMC on behalf of the RO' WHERE name = 'revalidation:submit:on:behalf:of:ro';
UPDATE `Permission` SET `type` = 'REVALIDATION', `description` ='Can submit a recommendation to GMC, must be an RO' WHERE name = 'revalidation:submit:to:gmc';
UPDATE `Permission` SET `type` = 'REVALIDATION', `description` ='Can submit a recommendation for RO review' WHERE name = 'revalidation:submit:to:ro:review';
UPDATE `Permission` SET `type` = 'PCS', `description` ='Can create and modify scaffolded entities' WHERE name = 'tcs:add:modify:entities';
UPDATE `Permission` SET `type` = 'INTERNAL', `description` ='Can delete scaffolded entities' WHERE name = 'tcs:delete:entities';
UPDATE `Permission` SET `type` = 'PCS', `description` ='Can view scaffolded entities' WHERE name = 'tcs:view:entities';
UPDATE `Permission` SET `type` = 'INTERNAL', `description` ='Used by the ETL to register new trainees with the profile service' WHERE name = 'trainee-id:register:trainee';
UPDATE `Permission` SET `type` = 'INTERNAL', `description` ='Used by the ETL to retrieve tis-id to gmc-id mappings' WHERE name = 'trainee-id:view:all:mappings';
