DROP TABLE IF EXISTS EqualityAndDiversity;
DROP TABLE IF EXISTS GdcDetails;
DROP TABLE IF EXISTS GmcDetails;
DROP TABLE IF EXISTS Immigration;
DROP TABLE IF EXISTS ManageRecord;
DROP TABLE IF EXISTS Person;
DROP TABLE IF EXISTS PersonalDetails;
DROP TABLE IF EXISTS Qualification;