ALTER TABLE IdMap ADD COLUMN active TINYINT(1) DEFAULT 1;
ALTER TABLE IdMap ADD COLUMN dateAdded DATE;
ALTER TABLE IdMap ADD COLUMN designatedBodyCode VARCHAR(20);

ALTER TABLE IdMap RENAME TraineeProfile;



